# Generated by Django 5.0.2 on 2024-02-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название услуги')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='описание услуги')),
                ('salary', models.PositiveIntegerField(verbose_name='стоимость услуги (р)')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.shift', verbose_name='смена')),
            ],
        ),
    ]
