# Generated by Django 5.0.2 on 2024-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shiftservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftservices',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterField(
            model_name='shiftservices',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='описание услуги'),
        ),
    ]
